coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
