# Generated by Django 5.1.4 on 2024-12-22 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pre_growth_rate",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Pre-Injury Growth Rate",
                    ),
                ),
                (
                    "pre_aif",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Pre-Injury Adjustment Impact Factor",
                    ),
                ),
                (
                    "post_growth_rate",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Post-Injury Growth Rate",
                    ),
                ),
                (
                    "post_aif",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Post-Injury Adjustment Impact Factor",
                    ),
                ),
                (
                    "include_health_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Include Health Insurance Analysis"
                    ),
                ),
                (
                    "hi_start_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Health Insurance Start Year",
                    ),
                ),
                (
                    "hi_end_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Health Insurance End Year"
                    ),
                ),
                (
                    "hi_base_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Health Insurance Base Premium",
                    ),
                ),
                (
                    "hi_growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Health Insurance Growth Rate",
                    ),
                ),
                (
                    "hi_discount_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Health Insurance Discount Rate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Economic Analyses",
            },
        ),
        migrations.CreateModel(
            name="PostInjuryRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "portion_of_year",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("age", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wage_base_years",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_injury_rows",
                        to="calculator.economicanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="PreInjuryRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "portion_of_year",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("age", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wage_base_years",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_injury_rows",
                        to="calculator.economicanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["year"],
            },
        ),
    ]
