# Generated by Django 5.1.4 on 2024-12-22 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_remove_preinjuryrow_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicanalysis",
            name="post_discount_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=3.0,
                help_text="Enter as percentage (e.g., 3.00 for 3.00%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Post-Injury Discount Rate (%)",
            ),
        ),
    ]
