# Generated by Django 5.1.4 on 2024-12-22 12:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preinjuryrow",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="economicanalysis",
            name="hi_end_year",
        ),
        migrations.RemoveField(
            model_name="economicanalysis",
            name="hi_start_year",
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date(1990, 1, 1), verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="date_of_injury",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date of Injury"
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="date_of_report",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date of Report"
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="post_base_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=40000.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Post-Injury Base Earnings ($)",
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="pre_base_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=50000.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pre-Injury Base Earnings ($)",
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="worklife_end_date",
            field=models.DateField(
                default=datetime.date(2050, 1, 1), verbose_name="Worklife End Date"
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="hi_base_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Health Insurance Base Premium ($)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="hi_discount_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0.0,
                help_text="Enter as percentage (e.g., 3.00 for 3.00%)",
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Health Insurance Discount Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="hi_growth_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0.0,
                help_text="Enter as percentage (e.g., 7.00 for 7.00%)",
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Health Insurance Growth Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="post_aif",
            field=models.DecimalField(
                decimal_places=4,
                default=50.0,
                help_text="Enter as percentage (e.g., 75.40 for 75.40%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Post-Injury Adjustment Impact Factor (%)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="post_growth_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=3.0,
                help_text="Enter as percentage (e.g., 4.20 for 4.20%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Post-Injury Growth Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="pre_aif",
            field=models.DecimalField(
                decimal_places=4,
                default=50.0,
                help_text="Enter as percentage (e.g., 75.40 for 75.40%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Pre-Injury Adjustment Impact Factor (%)",
            ),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="pre_growth_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=3.0,
                help_text="Enter as percentage (e.g., 4.20 for 4.20%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Pre-Injury Growth Rate (%)",
            ),
        ),
        migrations.DeleteModel(
            name="PostInjuryRow",
        ),
        migrations.DeleteModel(
            name="PreInjuryRow",
        ),
    ]
