# Generated by Django 5.1.4 on 2024-12-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("date_of_injury", models.DateField()),
                ("date_of_report", models.DateField()),
                (
                    "worklife_expectancy",
                    models.DecimalField(
                        decimal_places=2, help_text="Format: 00.00 years", max_digits=4
                    ),
                ),
                (
                    "years_to_final_separation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Years until final separation",
                        max_digits=4,
                    ),
                ),
                (
                    "life_expectancy",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Life expectancy in years",
                        max_digits=4,
                    ),
                ),
                (
                    "pre_growth_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("pre_aif", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "post_growth_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("post_aif", models.DecimalField(decimal_places=4, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostInjuryRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "portion_of_year",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("age", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wage_base_years",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_injury_rows",
                        to="calculator.economicanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="PreInjuryRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "portion_of_year",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("age", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wage_base_years",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_injury_rows",
                        to="calculator.economicanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["year"],
            },
        ),
    ]
