# Generated by Django 5.1.4 on 2024-12-23 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_cleanup_economic_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="economicanalysis",
            name="has_residual_capacity",
        ),
        migrations.RemoveField(
            model_name="economicanalysis",
            name="residual_base_wage",
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="post_injury_base_wage",
            field=models.FloatField(
                default=0.0,
                help_text="Base annual wage after injury (0 if total loss)",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluee",
            unique_together={("first_name", "last_name", "date_of_birth")},
        ),
    ]
