# Generated by Django 5.1.4 on 2024-12-24 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_economicanalysis_annual_health_contribution_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="economicanalysis",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Economic Analysis",
                "verbose_name_plural": "Economic Analyses",
            },
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="benefits_rate",
            field=models.FloatField(
                default=0.0,
                help_text="Benefits rate as a percentage of base wage",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="health_insurance_base",
            field=models.FloatField(
                default=0.0,
                help_text="Base annual health insurance cost",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="pension_base",
            field=models.FloatField(
                default=0.0,
                help_text="Base annual pension contribution",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
