# Generated by Django 5.0 on 2024-12-26 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_alter_economicanalysis_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthcareCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "growth_rate",
                    models.FloatField(
                        help_text="Annual growth rate for this category",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "frequency_years",
                    models.FloatField(
                        help_text="How often this treatment occurs (in years). Use 1 for annual, 0.5 for semi-annual, etc.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Healthcare Category",
                "verbose_name_plural": "Healthcare Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HealthcarePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_cost",
                    models.FloatField(
                        help_text="Base cost for this treatment",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this healthcare plan is included in the analysis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="healthcare_plans",
                        to="calculator.economicanalysis",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="calculator.healthcarecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Healthcare Plan",
                "verbose_name_plural": "Healthcare Plans",
                "ordering": ["category__name"],
            },
        ),
        migrations.CreateModel(
            name="HealthcareCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("age", models.FloatField()),
                (
                    "cost",
                    models.FloatField(
                        help_text="Calculated cost for this year",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="calculator.healthcareplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Healthcare Cost",
                "verbose_name_plural": "Healthcare Costs",
                "ordering": ["year"],
                "unique_together": {("plan", "year")},
            },
        ),
    ]
