# Generated by Django 5.1.4 on 2024-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_remove_economicanalysis_has_residual_capacity_and_more"),
        ("calculator", "0006_evaluee_unique_together"),
    ]

    operations = []
