# Generated by Django 5.1.4 on 2024-12-23 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0008_economicanalysis_annual_contribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicanalysis",
            name="annual_health_contribution",
            field=models.FloatField(
                blank=True,
                help_text="Annual employer contribution to health insurance",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="health_cost_inflation_rate",
            field=models.FloatField(
                blank=True,
                help_text="Annual health insurance cost inflation rate",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="economicanalysis",
            name="include_health_insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="economicanalysis",
            name="post_injury_base_wage",
            field=models.FloatField(
                help_text="Base annual wage after injury",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
